acord = [
    ["быть", "be", "was (ед. число), were (множ. число)", "been"],
    ["становится", "become", "became", "become"],
    ["начинать", "begin", "began", "begun"],
    ["кусаться", "bite", "bit", "bitten or bit"],
    ["дуть", "blow", "blew", "blown"],
    ["ломать", "break", "broke", "broken"],
    ["приносить", "bring", "brought", "brought"],
    ["строить", "build", "built", "built"],
    ["покупать", "buy", "bought", "bought"],
    ["ловить", "catch", "caught", "caught"],
    ["выбирать", "choose", "chose", "chosen"],
    ["приходить", "come", "came", "come"],
    ["стоить", "cost", "cost", "cost"],
    ["резать", "cut", "cut", "cut"],
    ["делать", "do (или 3-е лицо, ед. число – does)", "did", "done"],
    ["рисовать, тянуть", "draw", "drew", "drawn"],
    ["пить", "drink", "drank", "drunk"],
    ["водить автомобиль", "drive", "drove", "driven"],
    ["есть", "eat", "ate", "eaten"],
    ["падать", "fall", "fell", "fallen"],
    ["чувствовать", "feel", "felt", "felt"],
    ["находить", "find", "found", "found"],
    ["летать", "fly", "flew", "flown"],
    ["забывать", "forget", "forgot", "forgotten"],
    ["застывать, замерзать, замораживать", "freeze", "froze", "frozen"],
    ["получать", "get", "got", "got or gotten"],
    ["давать", "give", "gave", "given"],
    ["идти", "go", "went", "gone"],
    ["расти", "grow", "grew", "grown"],
    ["иметь", "have (или 3-е лицо, ед. число – has)", "had", "had"],
    ["слышать", "hear", "heard", "heard"],
    ["прятать", "hide", "hid", "hidden"],
    ["попадать, ударять", "hit", "hit", "hit"],
    ["держать", "hold", "held", "held"],
    ["причинять боль", "hurt", "hurt", "hurt"],
    ["содержать, поддерживать", "keep", "kept", "kept"],
    ["знать", "know", "knew", "known"],
    ["учиться, узнавать", "learn", "learned or learnt", "learned or learnt"],
    ["покидать, оставлять", "leave", "left", "left"],
    ["давать в займы", "lend", "lent", "lent"],
    ["позволять", "let", "let", "let"],
    ["лежать", "lie", "lay", "lain"],
    ["терять", "lose", "lost", "lost"],
    ["делать, мастерить", "make", "made", "made"],
    ["значить, иметь ввиду", "mean", "meant", "meant"],
    ["встречать, знакомиться", "meet", "met", "met"],
    ["платить", "pay", "paid", "paid"],
    ["класть, ставить", "put", "put", "put"],
    ["читать", "read", "read", "read"],
    ["ездить верхом", "ride", "rode", "ridden"],
    ["звонить", "ring", "rang", "rung"],
    ["бежать", "run", "ran", "run"],
    ["сказать", "say", "said", "said"],
    ["видеть", "see", "saw", "seen"],
    ["продавать", "sell", "sold", "sold"],
    ["посылать", "send", "sent", "sent"],
    ["светить, сиять", "shine", "shone or shined", "shone or shined"],
    ["стрелять", "shoot", "shot", "shot"],
    ["показывать", "show", "showed", "shown or showed"],
    ["петь", "sing", "sang or sung", "sung"],
    ["погружаться, опускаться", "sink", "sank or sunk", "sunk"],
    ["сидеть", "sit", "sat", "sat"],
    ["спать", "sleep", "slept", "slept"],
    ["пахнуть, нюхать, ощущать запах", "smell", "smelled or smelt", "smelled or smelt"],
    ["говорить", "speak", "spoke", "spoken"],
    ["произносить или писать по буквам", "spell", "spelled or spelt", "spelled or spelt"],
    ["тратить", "spend", "spent", "spent"],
    ["разлить", "spill", "spilled or spilt", "spilled or spilt"],
    ["стоять", "stand", "stood", "stood"],
    ["плавать", "swim", "swam", "swum"],
    ["брать, взять", "take", "took", "taken"],
    ["обучать", "teach", "taught", "taught"],
    ["рассказывать", "tell", "told", "told"],
    ["думать", "think", "thought", "thought"],
    ["бросать", "throw", "threw", "thrown"],
    ["понимать", "understand", "understood", "understood"],
    ["будить", "wake", "woke or waked", "woken or waked also woke"],
    ["носить, одевать", "wear", "wore", "worn"],
    ["побеждать", "win", "won", "won"],
    ["писать", "write", "wrote", "written"],
    ["пребывать, терпеть, соблюдать", "abide", "abode or abided", "abode or abided"],
    ["возникать, появляться", "arise", "arose", "arisen"],
    ["нести, рожать", "bear", "bore", "born or borne"],
    ["бить", "beat", "beat", "beaten"],
    ["гнуть", "bend", "bent", "bent"],
    ["держать пари", "bet", "bet", "bet or betted"],
    ["предлагать цену, назначать ставку", "bid", "bid", "bid"],
    ["просить, поручать, приглашать, приказывать", "bid (1)", "bade", "bidden"],
    ["связывать", "bind", "bound", "bound"],
    ["кровоточить", "bleed", "bled", "bled"],
    ["выращивать", "breed", "bred", "bred"],
    ["вещать по радио, телевидению", "broadcast", "broadcast or broadcasted", "broadcast or broadcasted"],
    ["гореть, жечь", "burn", "burnt or burned", "burnt or burned"],
    ["взрываться", "burst", "burst or bursted", "burst or bursted"],
    ["мочь, быть в состоянии", "can", "could", "(been able)"],
    ["бросать, проводить кастинг", "cast", "cast", "cast"],
    ["цепляться, липнуть", "cling", "clung", "clung"],
    ["одевать(ся)", "clothe", "clad or clothed", "clad or clothed"],
    ["ползти", "creep", "crept", "crept"],
    ["осмелится, посметь", "dare", "(устар. durst) dared", "dared"],
    ["вести дела", "deal", "dealt", "dealt"],
    ["копать", "dig", "dug", "dug"],
    ["нырять, погружаться", "dive", "dived or dove", "dived or dove"],
    ["мечтать, грезить", "dream", "dreamed or dreamt", "dreamed or dreamt"],
    ["жить, обитать, пребывать", "dwell", "dwelt or dwelled", "dwelt or dwelled"],
    ["кормить", "feed", "fed", "fed"],
    ["бороться", "fight", "fought", "fought"],
    ["подходить, подгонять (по размеру)", "fit", "fitted or fit", "fitted or fit"],
    ["сбежать", "flee", "fled", "fled"],
    ["швырять, бросать, бросаться", "fling", "flung", "flung"],
    ["запрещать", "forbid", "forbad or forbade(2)", "forbidden"],
    ["предсказывать, предугадывать", "forecast", "forecast or forecasted", "forecast or forecasted"],
    ["простить", "forgive", "forgave", "forgiven"],
    ["предвидеть", "foresee", "foresaw", "foreseen"],
    ["предсказывать, прогнозировать", "foretell", "foretold", "foretold"],
    ["оставлять, покидать", "forsake", "forsook", "forsaken"],
    ["точить, молоть", "grind", "ground", "ground"],
    ["висеть", "hang", "hung (hanged – в знач. вешать, казнить)", "hung (hanged – в знач. вешать, казнить)"],
    ["вырубать, прорубать", "hew", "hewed", "hewed or hewn"],
    ["становиться на колени", "kneel", "knelt or kneeled", "knelt or kneeled"],
    ["вязать, плести", "knit", "knit or knitted", "knit or knitted"],
    ["класть, стелить", "lay", "laid", "laid"],
    ["вести, лидировать", "lead", "led", "led"],
    ["перепрыгивать, скакать", "leap", "leaped or leapt", "leaped or leapt"],
    ["лгать (это правильный глагол, приведён здесь только для сравнения)", "lie", "lied", "lied"],
    ["зажигать, освещать", "light", "lit or lighted", "lit or lighted"],
    ["внушать недоверие, опасения", "misgive", "misgave", "misgiven"],
    ["ослышаться", "mishear", "misheard", "misheard"],
    ["промахнуться", "mishit", "mishit", "mishit"],
    ["класть не на место, потерять", "mislay", "mislaid", "mislaid"],
    ["ввести в заблуждение", "mislead", "misled", "misled"],
    ["неправильно истолковывать (или читать)", "misread", "misread", "misread"],
    ["писать с ошибками", "misspell", "misspelled (misspelt)", "misspelled (misspelt)"],
    ["неправильно понимать", "misunderstand", "misunderstood", "misunderstood"],
    ["заблуждаться, ошибаться", "mistake", "mistook", "mistaken"],
    ["косить", "mow", "mowed", "mowed or mown"],
    ["возмещать, дополнять", "offset", "offset", "offset"],
    ["перебивать цену, предлагать больше", "outbid", "outbid", "outbid"],
    ["превосходить", "outdo", "outdid", "outdone"],
    ["перегонять, опережать", "outrun", "outran", "outrun"],
    ["преодолеть, победить", "overcome", "overcame", "overcome"],
    ["превышать кредит, превышать бюджет", "overdraw", "overdrew", "overdrawn"],
    ["умолять, просить (о помощи и т.д.)", "plead", "pleaded or (plead / pled)", "pleaded or (plead / pled)"],
    ["доказывать, подтверждать", "prove", "proved", "proven or proved"],
    ["выходить, покидать, бросать", "quit", "quit or quitted", "quit or quitted"],
    ["делать сброс, возвращать в исходное состояние", "reset", "reset", "reset"],
    ["избавлять", "rid", "rid or ridded", "rid or ridded"],
    ["восходить, подниматься", "rise", "rose", "risen"],
    ["добиваться, искать", "seek", "sought", "sought"],
    ["сажать, устанавливать", "set", "set", "set"],
    ["шить", "sew", "sewed", "sewn or sewed"],
    ["трясти", "shake", "shook", "shaken"],
    ["бриться", "shave", "shaved", "shaved or shaven"],
    ["стричь", "shear", "sheared", "sheared or shorn"],
    ["проливать, избавляться от чего-д", "shed", "shed", "shed"],
    ["сжиматься", "shrink", "shrank or shrunk", "shrunk or shrunken"],
    ["закрывать, захлопывать", "shut", "shut", "shut"],
    ["убивать (тж. переносн. – сразить наповал.)", "slay", "slew (в переносном смысле slayed)", "slain (в переносном смысле slayed)"],
    ["скользить", "slide", "slid", "slid"],
    ["бросать, швырять", "sling", "slung", "slung"],
    ["разбить, сразить", "smite", "smote", "smitten"],
    ["ехать или бежать очень быстро, мчаться, спешить", "speed", "sped or speeded", "sped or speeded"],
    ["крутить, прясть", "spin", "spun", "spun"],
    ["плевать", "spit", "spit or spat", "spit or spat"],
    ["разделять, раскалывать", "split", "split", "split"],
    ["портить", "spoil", "spoiled or spoilt", "spoiled or spoilt"],
    ["распахнуть, распространять", "spread", "spread", "spread"],
    ["прыгать, скакать", "spring", "sprang or sprung", "sprung"],
    ["воровать", "steal", "stole", "stolen"],
    ["втыкать, прилепить(ся)", "stick", "stuck", "stuck"],
    ["жалить", "sting", "stung", "stung"],
    ["вонять", "stink", "stank", "stunk"],
    ["бастовать, ударять", "strike", "struck", "struck or stricken"],
    ["нанизывать, натянуть", "string", "strung", "strung"],
    ["клясться, ругаться", "swear", "swore", "sworn"],
    ["подметать", "sweep", "swept", "swept"],
    ["разбухать, надуваться", "swell", "swelled", "swollen or swelled"],
    ["качать", "swing", "swung", "swung"],
    ["рвать", "tear", "tore", "torn"],
    ["толкать, совать, колоть", "thrust", "thrust", "thrust"],
    ["ступать, топтать", "tread", "trod or treaded", "trodden or trod"],
    ["подрезать; сбивать цены", "undercut", "undercut", "undercut"],
    ["подвергаться, претерпевать", "undergo", "underwent", "undergone"],
    ["отменять, уничтожать, расстёгивать", "undo", "undid", "undone"],
    ["поддерживать, утверждать", "uphold", "upheld", "upheld"],
    ["опрокинуть, расстроиться", "upset", "upset", "upset"],
    ["перехватывать, подстерегать", "waylay", "waylaid", "waylaid"],
    ["ткать", "weave", "wove or weaved", "woven or weaved"],
    ["жениться, выходить или выдавать замуж", "wed", "wed", "wed or wedded"],
    ["плакать, запотевать", "weep", "wept", "wept"],
    ["мочить, увлажнять", "wet", "wet or wetted", "wet or wetted"],
    ["(вспомогательный глагол будущего времени) буду, будешь, будем, будет, будут", "will", "would", "-"],
    ["заводить (часы), наматывать", "wind", "wound", "wound"],
    ["противостоять", "withstand", "withstood", "withstood"],
    ["скрутить, сжимать, выжимать", "wring", "wrung", "wrung"],
]